# Generated by Django 4.2.7 on 2025-08-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
