# Generated by Django 4.2.7 on 2025-08-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_article_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
